/*
* Generated file
*
* Generated from: yang module name: my-custom-netconf-impl yang module local name: my-custom-netconf-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Wed Feb 24 14:56:15 CET 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package org.sdnhub.odl.tutorial.my.custom.netconf.impl;
public class TutorialNetconfExerciseModuleFactory extends org.sdnhub.odl.tutorial.my.custom.netconf.impl.AbstractTutorialNetconfExerciseModuleFactory {

}
