/*
* Generated file
*
* Generated from: yang module name: my-custom-netconf-impl yang module local name: my-custom-netconf-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Wed Feb 24 14:56:15 CET 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package org.sdnhub.odl.tutorial.my.custom.netconf.impl;
public interface TutorialNetconfExerciseModuleMXBean {
    public javax.management.ObjectName getNotificationService();

    public void setNotificationService(javax.management.ObjectName notificationService);

    public javax.management.ObjectName getBindingAwareBroker();

    public void setBindingAwareBroker(javax.management.ObjectName bindingAwareBroker);

    public javax.management.ObjectName getRpcRegistry();

    public void setRpcRegistry(javax.management.ObjectName rpcRegistry);

    public javax.management.ObjectName getDataBroker();

    public void setDataBroker(javax.management.ObjectName dataBroker);

}
